### ISSUE TITLE
Where are the enhanced videos saved?

### ISSUE THREAD

**Issue by supriyaarun27** [RyanXingQL/MFQEv2.0#11]
Hi, i just tested on my own video. I was able to get the metrics, but where is the enhanced video saved?

**Comment by RyanXingQL** [comment]
Hi supriyaarun27

As indicated in https://github.com/RyanXingQL/MFQEv2.0/blob/ac52631dee57070556060af18122609460184c8c/main_test.py#L306-L310, you may have to convert the enhanced numpy array by your own.
Sorry for the inconvenience.

For convertion, you can refer to https://github.com/RyanXingQL/PythonUtils/blob/main/conversion.py.

I may fix that if I have time later.

**Comment by supriyaarun27** [comment]
Thank you! Appreciate it

**Comment by RyanXingQL** [comment]
You're welcome
