### ISSUE TITLE
关于压缩比的问题

### ISSUE THREAD

**Issue by woaicv** [ryanxingql/mfqev2.0#13]
您好，我不是太懂压缩，老师跟我提了下压缩比，是不是有压缩比的相关概念。这个qp = 37的压缩比大概能达到多少？非常感谢！

**Comment by ryanxingql** [comment]
你好，我也不了解 HEVC LDP QP=37 的压缩比；您可以去查一下 HEVC 的报告或论文，或者自己试试，把 HM 压出来的码流和原始输入文件的存储大小做个对比。

**Comment by woaicv** [comment]
好的，非常感谢您的解答，我准备按照您的建议看看
