### ISSUE TITLE
自定义测试视频的要求

### ISSUE THREAD

**Issue by linyu92** [RyanXingQL/MFQEv2.0#14]
测试的压缩视频需要全intra编码么？还是说没有限制，在有帧间参考存在的情况下，也可以得到增强？

**Comment by ryanxingql** [comment]
您好 也能增强 但mfqe方法特别适用于帧间质量波动大的情况 帧内模式下增益小一些，关键帧也不是很好选择

**Comment by linyu92** [comment]
好的，谢谢大佬百忙之中解答。我看了下速览写得很好，其中有个QPF的检测网络有点想法。我是从商业链路层面思考的哈，因为编码阶段已经知道了每一帧的质量，甚至是每个区域的质量，即QP分布，这些信息可以在编码的同时直接送进每一帧的SEI里存储，解码端可以直接利用，这样是不是就没有QPF的必要了。

**Comment by linyu92** [comment]
另外我有点思考不知道对不对，MFQE利用好帧增强差帧的思路跟HEVC里传统的帧间补偿算法有点类似（当前帧去参考相邻帧），但HEVC不能做类似旋转之类的仿射运动，而MFQE可以弥补这一点，所以可以在有inter存在的情况下，进一步得到增强

**Comment by ryanxingql** [comment]
> 好的，谢谢大佬百忙之中解答。我看了下速览写得很好，其中有个QPF的检测网络有点想法。我是从商业链路层面思考的哈，因为编码阶段已经知道了每一帧的质量，甚至是每个区域的质量，即QP分布，这些信息可以在编码的同时直接送进每一帧的SEI里存储，解码端可以直接利用，这样是不是就没有QPF的必要了。

您说的很对 如果能直接从编码信息中得到质量信息 是最好的

**Comment by ryanxingql** [comment]
> 另外我有点思考不知道对不对，MFQE利用好帧增强差帧的思路跟HEVC里传统的帧间补偿算法有点类似（当前帧去参考相邻帧），但HEVC不能做类似旋转之类的仿射运动，而MFQE可以弥补这一点，所以可以在有inter存在的情况下，进一步得到增强

您说的是一个方面。另一个方面，一些编码模式下是一定存在质量波动的，这种编码方式能节省码率。我们正是利用了这一特性

**Comment by linyu92** [comment]
> > 另外我有点思考不知道对不对，MFQE利用好帧增强差帧的思路跟HEVC里传统的帧间补偿算法有点类似（当前帧去参考相邻帧），但HEVC不能做类似旋转之类的仿射运动，而MFQE可以弥补这一点，所以可以在有inter存在的情况下，进一步得到增强
> 
> 您说的是一个方面。另一个方面，一些编码模式下是一定存在质量波动的，这种编码方式能节省码率。我们正是利用了这一特性

对 商业模式下一般是VBR或CBR，一般编码器的码控会给I帧分配的很高的码率，参考帧次之，非参考帧只有很小码率可以用，所以质量一般最差。
