### ISSUE TITLE
关于压缩视频的问题

### ISSUE THREAD

**Issue by wangweiran0922** [RyanXingQL/MFQEv2.0#15]
首先，感谢您对自己工作的开源。
其次，我在使用提供的压缩视频的代码中，出现了

WARNING: --SEIDecodedPictureHash is now disabled by default.
**Automatic verification of decoded pictures by a
   Automatic verification of decoded pictures by a

的警告，
想请问下我是在哪步配置出现错误了吗？

**Comment by ryanxingql** [comment]
您好，感谢关注。这个警告通常是可忽视的，不用担心。

**Comment by wangweiran0922** [comment]
好的，谢谢您的回复
还有个问题，在dataset/mafqev2.py中第95和102行生成gt和lq的图像时，请问为什么生成的结果是1通道的呢？但是在最后return的结果却是([RGB],H,W)。这看起来是3通道的输出。
这个问题困扰我很久，希望能得到您的回复，谢谢。

**Comment by ryanxingql** [comment]
请问 `dataset/mafqev2.py` 是哪一个文件？可以给我一个网址链接吗，谢谢

**Comment by wangweiran0922** [comment]
你好，链接如下
https://github.com/ryanxingql/stdf-pytorch/blob/master/dataset/mfqev2.py

**Comment by ryanxingql** [comment]
您好。我的备注可能有问题。由于使用了 `_bytes2img`，其默认输入图像为灰度图像；因此返回的应该是单通道图像。

如果想使用 RGB 版本的 STDF，可以参考我的新仓库：https://github.com/ryanxingql/powerqe

**Comment by wangweiran0922** [comment]
您好，请问如果我想在此基础上将其从(H,W,1)改成（H,W,3）,应该修改哪个地方呢？

**Comment by ryanxingql** [comment]
1. 读取数据时应读取彩色图像;
2. 网络结构应改为 3 通道输入和输出。

**Comment by wangweiran0922** [comment]
好的，非常感谢您中肯的回复。
