### ISSUE TITLE
Calculation of SSIM

### ISSUE THREAD

**Issue by hoolyshit** [RyanXingQL/MFQEv2.0#2]
Hi. Thanks for sharing your nice works.

I am trying to reproduce results in the paper, but i can't find the function to calculate SSIM. Do you use skimage.measure.compare_ssim or other implementation?

Thanks in advance.

**Comment by RyanXingQL** [comment]
Yes, for simplicity.

**Comment by hoolyshit** [comment]
@RyanXingQL  Thanks for your reply.

Actually, I've tried using skimage.measure.compare_ssim to compute ΔSSIM as follow:
`ssim_ori += compare_ssim(Y[ite_frame], raw, data_range=255)`
`ssim_enh += compare_ssim(Y_enhanced[ite_frame]*255.0, raw, data_range=255)`
But the result does not match that in the paper (0.0161 in compare_ssim vs. 0.0096 in paper for sequence 'BasketballPass'). So I am wondering if I got something wrong here?

Thanks a lot!

**Comment by hoolyshit** [comment]
@RyanXingQL  Thank you for the reply.

Actually, I've tried using skimage.measure.compare_ssim to compute ΔSSIM as follow:
`ssim_ori += compare_ssim(Y[ite_frame], raw, data_range=255)`
`ssim_enh += compare_ssim(Y_enhanced[ite_frame]*255.0, raw, data_range=255`
But the result does not match that in the paper (0.0161 in compare_ssim versus 0.0096 in paper). So I'm wondering if I got something wrong here?

Thanks a lot!

**Comment by RyanXingQL** [comment]
@hoolyshit Thany you for your reply.
You are right, there is a mistake in our reported results. We will correct it in our later version.
Thank you again~
