### ISSUE TITLE
List of Training Sequence

### ISSUE THREAD

**Issue by hoolyshit** [RyanXingQL/MFQEv2.0#5]
@RyanXingQL , Hi.

Would you mind sharing the names of 106 training sequences?  Since there are a lot more than 106 sequences in Xiph or VQEG datasets.

It would be nice for reproduction or fair comparison in subsequent works.

Thank you！

**Comment by RyanXingQL** [comment]
108 videos for training:
11skateboarding-10_1920x1080_87.yuv
11skateboarding-15_1920x1080_89.yuv
11skateboarding-5_1920x1080_51.yuv
14airacrobatics-2_1920x1080_2173.yuv
14airacrobatics-3_1920x1080_697.yuv
18ANIMALS-12_1920x1080_168.yuv
18ANIMALS-1_1920x1080_330.yuv
18ANIMALS-5_1920x1080_288.yuv
18ANIMALS-6_1920x1080_228.yuv
18ANIMALS-7_1920x1080_326.yuv
3fjords-1_1920x1080_880.yuv
3fjords-2_1920x1080_1606.yuv
5costa_1920x1080_468.yuv
7monkey4_1920x1080_217.yuv
7monkey7_1920x1080_484.yuv
8americanfootball-6_1920x1080_374.yuv
8americanfootball-7_1920x1080_392.yuv
Cactus_1920x1080_189.yuv
Coastguard_1920x1080_150.yuv
Foreman_1920x1080_248.yuv
LiquidAssets-blackandwhitefish_1920x1080_570.yuv
LiquidAssets-blackfish-original_1920x1080_552.yuv
LiquidAssets-camofish-original_1920x1080_573.yuv
LiquidAssets-eels-original_1920x1080_499.yuv
LiquidAssets-greenanemone-original_1920x1080_414.yuv
Netflix-BoxingPractice_2048x1080_254.yuv
Netflix-Crosswalk_2048x1080_300.yuv
Netflix-DrivingPOV_2048x1080_1199.yuv
Netflix-Narrator_2048x1080_300.yuv
Netflix-RollerCoaster_2048x1080_1199.yuv
Netflix-Tango_2048x1080_294.yuv
akiyo_352x288_300.yuv
bus_352x288_150.yuv
city_704x576_600.yuv
coastguard_352x288_300.yuv
cont_1920x1080_120.yuv
crew_704x576_600.yuv
crowdrun_1920x1080_500.yuv
deadline_352x288_1374.yuv
female_1920x1080_150.yuv
football_352x288_260.yuv
football_720x480_360.yuv
foreman_352x288_300.yuv
garden_352x240_115.yuv
hallmonitor_352x288_300.yuv
harbour_704x576_600.yuv
husky_352x288_250.yuv
ice_704x576_480.yuv
in-to-tree_1920x1080_500.yuv
intros_720x480_360.yuv
mad900_352x288_900.yuv
male_1920x1080_150.yuv
mobile-calendar_720x480_360.yuv
mobile_352x288_300.yuv
mother-daughter_352x288_300.yuv
mpr-BusB4-original_1920x1080_571.yuv
news_352x288_300.yuv
old-town-cross_1920x1080_500.yuv
paris_352x288_1065.yuv
pedestrian-area_1920x1080_375.yuv
sign-irene_352x288_540.yuv
silent_352x288_300.yuv
simo_1920x1080_200.yuv
soccer_704x576_600.yuv
stefan_352x240_300.yuv
students_352x288_1007.yuv
tempete_352x288_260.yuv
touchdown-pass_1920x1080_570.yuv
tractor_1920x1080_690.yuv
videoSRC001_640x360_150.yuv
videoSRC006_640x360_150.yuv
videoSRC007_640x360_150.yuv
videoSRC009_640x360_150.yuv
videoSRC013_640x360_150.yuv
videoSRC018_640x360_150.yuv
videoSRC056_640x360_150.yuv
videoSRC058_640x360_150.yuv
videoSRC063_640x360_150.yuv
videoSRC067_640x360_150.yuv
videoSRC069_640x360_150.yuv
videoSRC070_640x360_150.yuv
videoSRC072_640x360_150.yuv
videoSRC078_640x360_150.yuv
videoSRC080_640x360_150.yuv
videoSRC082_640x360_150.yuv
videoSRC102_640x360_120.yuv
videoSRC106_640x360_120.yuv
videoSRC116_640x360_120.yuv
videoSRC120_640x360_120.yuv
videoSRC127_640x360_150.yuv
videoSRC140_640x360_120.yuv
videoSRC144_640x360_120.yuv
videoSRC151_640x360_150.yuv
videoSRC153_640x360_150.yuv
videoSRC157_640x360_150.yuv
videoSRC159_640x360_120.yuv
videoSRC160_640x360_120.yuv
videoSRC162_640x360_120.yuv
videoSRC173_640x360_120.yuv
videoSRC177_640x360_120.yuv
videoSRC178_640x360_120.yuv
videoSRC183_640x360_120.yuv
videoSRC197_640x360_120.yuv
videoSRC199_640x360_120.yuv
videoSRC203_640x360_120.yuv
videoSRC206_640x360_120.yuv
vtc1nw_720x480_360.yuv
waterfall_352x288_260.yuv

**Comment by hoolyshit** [comment]
Thanks a lot!

**Comment by hoolyshit** [comment]
@RyanXingQL  Sorry to bother you again.

I have successfully found and downloaded some of the videos in Xiph.org dataset. However, I can't find those videos in format "videoSRCxxx_640x360_xxx.yuv". Are those the original names of videos, or you renamed and somehow sorted them? Are there any URLs linked to those videos directly?

Thanks!

**Comment by RyanXingQL** [comment]
I can provide you the Baidu Netdisk link to download these 108 videos. Give me your email please~

**Comment by hoolyshit** [comment]
@RyanXingQL 
My email: martinhs90@outlook.com

Thank you!
