### ISSUE TITLE
Can you share the code to generate PQF_Labels and ApprQP_labels?

### ISSUE THREAD

**Issue by zabir-nabil** [RyanXingQL/MFQEv2.0#7]
It seems you have some numpy arrays pre-saved in the directory for those specific videos. How can I generate PQF_Labels for new videos (in case I don't have the raw version)?

**Comment by RyanXingQL** [comment]
Hi zabir-nabil.
We use 38 features (36 of which are generated by a no-reference quality assessment method, and the other 2 features are QP and bitrate) and Bi-LSTM to detect PQF.
During our experiments, we find that QP is the key feature. You can detect PQF simply according to the QP of each frame.
The 36 features generated by the NR QA method (subjective quality score) are not consistent with the PSNR results (objective quality score), so they are not that important. For details and code about this QA method, please refer to _Study of subjective and objective quality assessment of video_. Finally, the training of Bi-LSTM is very fast.

**Comment by zabir-nabil** [comment]
Thank you for your answer, so if I understand you - I can find the PSNR curve from QP values of each frame only. Then why do I need the Bi-LSTM detector if QP can give me the frames with highest and lowest PSNR (I'm assuming PSNR is directly related with QP)?
Can you give me a link to any resource which has implementation details (python code) for calculating QP for each frame?

**Comment by RyanXingQL** [comment]
> Thank you for your answer, so if I understand you - I can find the PSNR curve from QP values of each frame only. Then why do I need the Bi-LSTM detector if QP can give me the frames with highest and lowest PSNR (I'm assuming PSNR is directly related with QP)?
> Can you give me a link to any resource which has implementation details (python code) for calculating QP for each frame?

QP (quantization parameter) is one of the basic informations generated by video codec and can be directly extracted from bit flow. Therefore, our MFQE approach targets mainly on compressed video (so the bit flow is available).
We recently find that QP is the key factor when detecting PQF. Without QP information, the detection accuracy may drop to 60~70%.
If you have no QP information, we suggest that you can search for some objective quality assessment approaches especially for compression artifacts, e.g. _No-reference quality assessment of deblocked images_, 2016 Neurocomputing. You can also consider other sota approaches based on Conv-LSTM etc that are with no need for quality assessment.

**Comment by zabir-nabil** [comment]
Okay, I'm looking into the paper for more details. In the meantime, kindly share the feature extraction and label generation code or any reference if possible [Could you kindly email me if that's an option: zabiralnazi@yahoo.com].
Thanks
